# Generated by Django 4.2.16 on 2026-04-07 06:02

from django.db import migrations, models, connection
import django.db.models.deletion


def create_message_model_if_not_exists(apps, schema_editor):
    # Check if the table already exists
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_name = 'nea_loss_message'
            );
        """)
        table_exists = cursor.fetchone()[0]
    
    if not table_exists:
        # Only create the model if table doesn't exist
        Message = apps.get_model('nea_loss', 'Message')
        Message._meta.get_field('id').auto_created = True
        schema_editor.create_model(Message)


def reverse_message_model(apps, schema_editor):
    Message = apps.get_model('nea_loss', 'Message')
    schema_editor.delete_model(Message)


class Migration(migrations.Migration):

    dependencies = [
        ('nea_loss', '0010_add_dc_yearly_target'),
    ]

    operations = [
        migrations.RunPython(create_message_model_if_not_exists, reverse_message_model),
    ]
