# Generated by Django 4.2.16 on 2026-04-22 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nea_loss', '0011_auto_20260407_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('REPORT_SUBMITTED', 'Report Submitted'), ('REPORT_APPROVED', 'Report Approved'), ('REPORT_REJECTED', 'Report Rejected'), ('LOSS_EXCEEDED', 'Loss Target Exceeded'), ('REMINDER', 'Submission Reminder'), ('OVERRIDE_REQUESTED', 'Override Requested'), ('OVERRIDE_APPROVED', 'Override Approved'), ('OVERRIDE_REJECTED', 'Override Rejected')], max_length=30),
        ),
        migrations.CreateModel(
            name='DCReportOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_month', models.PositiveSmallIntegerField(choices=[(1, 'Shrawan'), (2, 'Bhadra'), (3, 'Ashwin'), (4, 'Kartik'), (5, 'Mangsir'), (6, 'Poush'), (7, 'Magh'), (8, 'Falgun'), (9, 'Chaitra'), (10, 'Baisakh'), (11, 'Jestha'), (12, 'Ashadh')])),
                ('skip_from_month', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Shrawan'), (2, 'Bhadra'), (3, 'Ashwin'), (4, 'Kartik'), (5, 'Mangsir'), (6, 'Poush'), (7, 'Magh'), (8, 'Falgun'), (9, 'Chaitra'), (10, 'Baisakh'), (11, 'Jestha'), (12, 'Ashadh')], null=True)),
                ('skip_to_month', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Shrawan'), (2, 'Bhadra'), (3, 'Ashwin'), (4, 'Kartik'), (5, 'Mangsir'), (6, 'Poush'), (7, 'Magh'), (8, 'Falgun'), (9, 'Chaitra'), (10, 'Baisakh'), (11, 'Jestha'), (12, 'Ashadh')], null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reason', models.TextField(help_text='Reason for override request (e.g., technical problems, system downtime)')),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes on approval/rejection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_overrides', to=settings.AUTH_USER_MODEL)),
                ('distribution_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_overrides', to='nea_loss.distributioncenter')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_overrides', to='nea_loss.fiscalyear')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('distribution_center', 'fiscal_year', 'resume_month')},
            },
        ),
    ]
