# Generated by Django 4.2.16 on 2026-04-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nea_loss', '0012_add_dc_report_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcreportoverride',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this override is currently active'),
        ),
    ]
