# Generated by Django 4.2.16 on 2026-05-12 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nea_loss', '0013_add_override_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='provincialreport',
            name='dmd_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='provincialreport',
            name='dmd_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provincialreport',
            name='dmd_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dmd_reviewed_provincial_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='provincialreport',
            name='submitted_to_dmd_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provincialreport',
            name='submitted_to_dmd_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_provincial_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='provincialreport',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED_TO_DMD', 'Submitted to DMD'), ('DMD_APPROVED', 'DMD Approved'), ('DMD_REJECTED', 'DMD Rejected')], default='DRAFT', max_length=20),
        ),
    ]
