# Generated by Django 4.2.16 on 2026-05-12 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nea_loss', '0014_add_dmd_approval_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DMDReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'Shrawan'), (2, 'Bhadra'), (3, 'Ashwin'), (4, 'Kartik'), (5, 'Mangsir'), (6, 'Poush'), (7, 'Magh'), (8, 'Falgun'), (9, 'Chaitra'), (10, 'Baisakh'), (11, 'Jestha'), (12, 'Ashadh')], default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FINALIZED', 'Finalized'), ('SUBMITTED', 'Submitted')], default='DRAFT', max_length=20)),
                ('total_loss_units', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_energy_received', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_energy_utilised', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('overall_loss_percent', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('submitted_to_management_at', models.DateTimeField(blank=True, null=True)),
                ('management_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('management_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dmd_reports', to='nea_loss.fiscalyear')),
                ('management_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='management_reviewed_dmd_reports', to=settings.AUTH_USER_MODEL)),
                ('submitted_to_management_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_dmd_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fiscal_year__year_ad_start', 'month'],
                'unique_together': {('fiscal_year', 'month')},
            },
        ),
    ]
