# Generated by Django 4.2.16 on 2026-05-14 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nea_loss', '0015_add_dmd_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeederRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('ADD', 'Add Feeder'), ('DELETE', 'Delete Feeder'), ('MODIFY', 'Modify Feeder')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('feeder_name', models.CharField(help_text='Name of the feeder', max_length=200)),
                ('source_type', models.CharField(blank=True, choices=[('SUBSTATION', 'Substation'), ('FEEDER_11KV', '11 kV Feeder'), ('FEEDER_33KV', '33 kV Feeder'), ('INTERBRANCH', 'Interbranch Import'), ('IPP', 'Independent Power Producer'), ('ENERGY_IMPORT', 'Energy Import'), ('EXPORT_DC', 'Export to Other DC'), ('EXPORT_IPP', 'Export to IPP'), ('ENERGY_EXPORT', 'Energy Export')], max_length=30)),
                ('voltage_level', models.CharField(blank=True, max_length=20)),
                ('multiplying_factor', models.DecimalField(blank=True, decimal_places=3, default=1, max_digits=10, null=True)),
                ('reason', models.TextField(help_text='Reason for this request')),
                ('provincial_notes', models.TextField(blank=True, help_text='Notes from provincial office')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_feeder_requests', to=settings.AUTH_USER_MODEL)),
                ('distribution_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeder_requests', to='nea_loss.distributioncenter')),
                ('meter_point', models.ForeignKey(blank=True, help_text='Existing feeder to delete', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeder_requests', to='nea_loss.meterpoint')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeder_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('REPORT_SUBMITTED', 'Report Submitted'), ('REPORT_APPROVED', 'Report Approved'), ('REPORT_REJECTED', 'Report Rejected'), ('LOSS_EXCEEDED', 'Loss Target Exceeded'), ('REMINDER', 'Submission Reminder'), ('OVERRIDE_REQUESTED', 'Override Requested'), ('OVERRIDE_APPROVED', 'Override Approved'), ('OVERRIDE_REJECTED', 'Override Rejected'), ('FEEDER_REQUESTED', 'Feeder Change Requested'), ('FEEDER_APPROVED', 'Feeder Change Approved'), ('FEEDER_REJECTED', 'Feeder Change Rejected')], max_length=30),
        ),
        migrations.DeleteModel(
            name='DMDReport',
        ),
    ]
