# Generated by Django 4.2.16 on 2026-05-19 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nea_loss', '0016_feederrequest_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DCSDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Picture of the DCS', null=True, upload_to='dcs_images/')),
                ('introduction', models.TextField(blank=True, help_text='Introduction/description of the DCS')),
                ('established_date', models.DateField(blank=True, help_text='Date when DCS was established', null=True)),
                ('coverage_area', models.TextField(blank=True, help_text='Geographical area covered by this DCS')),
                ('total_capacity', models.DecimalField(blank=True, decimal_places=2, help_text='Total capacity in kVA', max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distribution_center', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dcs_detail', to='nea_loss.distributioncenter')),
            ],
            options={
                'verbose_name': 'DCS Detail',
                'verbose_name_plural': 'DCS Details',
            },
        ),
        migrations.AddField(
            model_name='provincialoffice',
            name='edit_approval_password',
            field=models.CharField(blank=True, help_text='Password for approving DCS detail edit requests', max_length=100),
        ),
        migrations.CreateModel(
            name='DCSOfficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('designation', models.CharField(help_text='e.g., Chief, Deputy Chief, Engineer', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dcs_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officials', to='nea_loss.dcsdetail')),
            ],
            options={
                'verbose_name': 'DCS Official',
                'verbose_name_plural': 'DCS Officials',
                'ordering': ['designation', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DCSFeeder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the feeder', max_length=200)),
                ('feeder_code', models.CharField(blank=True, max_length=50)),
                ('voltage_level', models.CharField(blank=True, help_text='e.g., 11 kV, 33 kV', max_length=20)),
                ('length_km', models.DecimalField(blank=True, decimal_places=2, help_text='Length in kilometers', max_digits=10, null=True)),
                ('connected_load', models.DecimalField(blank=True, decimal_places=2, help_text='Connected load in kVA', max_digits=15, null=True)),
                ('transformer_count', models.IntegerField(blank=True, help_text='Number of transformers', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dcs_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeders', to='nea_loss.dcsdetail')),
            ],
            options={
                'verbose_name': 'DCS Feeder',
                'verbose_name_plural': 'DCS Feeders',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DCSDetailEditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_changes', models.JSONField(help_text='JSON object containing proposed changes')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if rejected')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_dcs_detail_edits', to=settings.AUTH_USER_MODEL)),
                ('dcs_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_requests', to='nea_loss.dcsdetail')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dcs_detail_edit_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DCS Detail Edit Request',
                'verbose_name_plural': 'DCS Detail Edit Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DCSConsumerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(help_text='e.g., Domestic, Commercial, Industrial', max_length=100)),
                ('consumer_count', models.IntegerField(default=0, help_text='Number of consumers in this category')),
                ('connected_load', models.DecimalField(decimal_places=2, default=0, help_text='Total connected load in kVA', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dcs_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumer_types', to='nea_loss.dcsdetail')),
            ],
            options={
                'verbose_name': 'DCS Consumer Type',
                'verbose_name_plural': 'DCS Consumer Types',
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='DCHistoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'Shrawan'), (2, 'Bhadra'), (3, 'Ashwin'), (4, 'Kartik'), (5, 'Mangsir'), (6, 'Poush'), (7, 'Magh'), (8, 'Falgun'), (9, 'Chaitra'), (10, 'Baisakh'), (11, 'Jestha'), (12, 'Ashadh')])),
                ('total_received_kwh', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_utilised_kwh', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_loss_kwh', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('loss_percent', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('total_consumers', models.IntegerField(default=0)),
                ('consumer_breakdown', models.JSONField(blank=True, help_text='JSON object with consumer category breakdown', null=True)),
                ('report_created_at', models.DateTimeField(help_text='When the report was created')),
                ('report_submitted_at', models.DateTimeField(blank=True, help_text='When the report was submitted', null=True)),
                ('report_approved_at', models.DateTimeField(blank=True, help_text='When the report was approved', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dc_manager', models.ForeignKey(blank=True, help_text='DC Manager at the time', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dc_history_entries', to=settings.AUTH_USER_MODEL)),
                ('distribution_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='nea_loss.distributioncenter')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='nea_loss.fiscalyear')),
                ('provincial_manager', models.ForeignKey(blank=True, help_text='Provincial Manager at the time', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provincial_history_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DC History Entry',
                'verbose_name_plural': 'DC History Entries',
                'ordering': ['-fiscal_year__year_ad_start', '-month', 'distribution_center__name'],
                'unique_together': {('distribution_center', 'fiscal_year', 'month')},
            },
        ),
    ]
