# Generated by Django 4.2.16 on 2026-06-08 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nea_loss', '0018_dcsdetaileditrequest_pending_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterpoint',
            name='linked_distribution_center',
            field=models.ForeignKey(blank=True, help_text='For ENERGY_IMPORT: source DC. For ENERGY_EXPORT/EXPORT_DC: destination DC. Used for cross-DC validation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_meter_points', to='nea_loss.distributioncenter'),
        ),
    ]
