# Generated by Django 4.2.16 on 2026-06-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nea_loss', '0019_meterpoint_linked_distribution_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterpoint',
            name='linked_distribution_center_name',
            field=models.CharField(blank=True, help_text='Free-text name of linked DC for cross-DC validation. Used when exact DC match is not found.', max_length=200),
        ),
    ]
