# Generated by Django 4.2.16 on 2026-06-12 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nea_loss', '0020_meterpoint_linked_distribution_center_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyExportDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_feeder_name', models.CharField(help_text='Name of the destination feeder', max_length=200)),
                ('destination_connection', models.CharField(blank=True, help_text='Substation/Grid/Powerhouse of destination', max_length=200)),
                ('destination_type', models.CharField(choices=[('SUBSTATION', 'Substation'), ('FEEDER_11KV', '11 kV Feeder'), ('FEEDER_33KV', '33 kV Feeder'), ('INTERBRANCH', 'Interbranch Import'), ('IPP', 'Independent Power Producer'), ('ENERGY_IMPORT', 'Energy Import'), ('EXPORT_DC', 'Export to Other DC'), ('EXPORT_IPP', 'Export to IPP'), ('ENERGY_EXPORT', 'Energy Export')], max_length=20)),
                ('destination_voltage', models.CharField(blank=True, max_length=20)),
                ('destination_mf', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('present_reading', models.DecimalField(decimal_places=3, max_digits=15)),
                ('previous_reading', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('difference', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('unit_kwh', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['destination_feeder_name'],
            },
        ),
        migrations.AddField(
            model_name='meterpoint',
            name='connection_source',
            field=models.CharField(blank=True, help_text='Substation/Grid/Powerhouse from which this feeder is connected', max_length=200),
        ),
        migrations.CreateModel(
            name='EnergyImportDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_feeder_name', models.CharField(help_text='Name of the source feeder', max_length=200)),
                ('source_connection', models.CharField(blank=True, help_text='Substation/Grid/Powerhouse of source', max_length=200)),
                ('source_type', models.CharField(choices=[('SUBSTATION', 'Substation'), ('FEEDER_11KV', '11 kV Feeder'), ('FEEDER_33KV', '33 kV Feeder'), ('INTERBRANCH', 'Interbranch Import'), ('IPP', 'Independent Power Producer'), ('ENERGY_IMPORT', 'Energy Import'), ('EXPORT_DC', 'Export to Other DC'), ('EXPORT_IPP', 'Export to IPP'), ('ENERGY_EXPORT', 'Energy Export')], max_length=20)),
                ('source_voltage', models.CharField(blank=True, max_length=20)),
                ('source_mf', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('present_reading', models.DecimalField(decimal_places=3, max_digits=15)),
                ('previous_reading', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('difference', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('unit_kwh', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_export_detail', models.ForeignKey(blank=True, help_text='Automatically linked export detail when this import matches an export', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_import_details', to='nea_loss.energyexportdetail')),
                ('meter_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_details', to='nea_loss.meterpoint')),
                ('monthly_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_import_details', to='nea_loss.monthlylossdata')),
            ],
            options={
                'ordering': ['source_feeder_name'],
                'unique_together': {('monthly_data', 'meter_point')},
            },
        ),
        migrations.AddField(
            model_name='energyexportdetail',
            name='linked_import_detail',
            field=models.ForeignKey(blank=True, help_text='Automatically linked import detail when this export matches an import', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_export_details', to='nea_loss.energyimportdetail'),
        ),
        migrations.AddField(
            model_name='energyexportdetail',
            name='meter_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_details', to='nea_loss.meterpoint'),
        ),
        migrations.AddField(
            model_name='energyexportdetail',
            name='monthly_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_export_details', to='nea_loss.monthlylossdata'),
        ),
        migrations.AlterUniqueTogether(
            name='energyexportdetail',
            unique_together={('monthly_data', 'meter_point')},
        ),
    ]
