# Generated by Django 4.2.16 on 2026-06-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nea_loss', '0021_energyexportdetail_meterpoint_connection_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feederrequest',
            name='connection_source',
            field=models.CharField(blank=True, help_text='Substation/Grid/Powerhouse from which this feeder is connected', max_length=200),
        ),
    ]
