# Generated by Django 4.2.16 on 2026-07-06 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nea_loss', '0022_feederrequest_connection_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeederFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeder_name', models.CharField(help_text='Name of the feeder', max_length=200)),
                ('file', models.FileField(help_text='Upload feeder file (PDF, Word, Excel)', upload_to='feeder_files/%Y/%m/')),
                ('file_type', models.CharField(choices=[('PDF', 'PDF'), ('WORD', 'Word Document'), ('EXCEL', 'Excel Spreadsheet'), ('IMAGE', 'Image'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Description of the file content')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeder_files', to='nea_loss.lossreport')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_feeder_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feeder File',
                'verbose_name_plural': 'Feeder Files',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
